### PR TITLE
Initial vault based credential store + Rest API framework with SSH and AWS credential support

### PR DESCRIPTION
**Pull request by DImuthuUpe**

### CODE REVIEW

**Comment by machristie** [comment]
@DImuthuUpe +1, looks good to me. I like the use of Spring Boot.

Some questions
- from the code looks like Vault clients have a token they use for authorization. Eventually we'll provide these in a config file? Also is it possible to do fine grained authorization with these tokens, for example, create a token that can only read keys for a specific tenant, i.e, can only read `/secret/ssh/seagrid/*` for example?

**Comment by DImuthuUpe** [comment]
@machristie Good question. Actually it should be the second stage of this implementation.
1. Externalizing vault credentials
2. Implementing policies and mapping it to auth methods in vault paths. https://learn.hashicorp.com/vault/getting-started/policies

Step 2 needs little bit of more research on how to cleanly do that but I'm confident that we can find a better approach.

**Comment by smarru** [comment]
@DImuthuUpe @machristie thoughts on merging this PR? more to be discussed?

**Comment by machristie** [comment]
@smarru it's a +1 from me. I'll leave it up to @DImuthuUpe whether this is ready to merge.

**Comment by DImuthuUpe** [comment]
Thanks @machristie. I need to add the License file as this is the first commit and then I'll merge this

**Pull request merged**
